#--------------------------------------------------------------------------------------------------
#
#                                 Groupware Global Properties
#
#
#--------------------------------------------------------------------------------------------------

################## Groupware Section ##################
gwVer=7.0
CMP_ID=C300210723

################## Database Section ##################
# oracle / mysql / mssql
dbtypeLowerCase=mysql
jndiName=java:comp/env/jdbc/NaonekpDS

################## JUNIT TEST Section ##################
jdbc.driverClassName=
jdbc.url=
jdbc.username=
jdbc.password=

################## Protocol section ##################
ngwProtocol=https://
EKP_PROTOCOL=https://

################## URL section ##################
ngwProtocolUrl=https://hanwaydev.hanjinkal.com
imageServer=https://hanwaydev.hanjinkal.com
mobileImageServer=https://hanwaydev.hanjinkal.com
mobilePrefix=m
MOBILE_HOST=m
MOBILE_MAIL_HOST=m
SKIN_URL=https://hanwaydev.hanjinkal.com
SKIN_ROOT=https://hanwaydev.hanjinkal.com/style
EKP_URL=https://hanwaydev.hanjinkal.com/ekp
LOGIN_URL=https://hanwaydev.hanjinkal.com/ekp/view/login/userLogin
WEB_SERVER=https://hanwaydev.hanjinkal.com
IMAGE_URL=https://hanwaydev.hanjinkal.com/ekp
DAV_OPENAPI_URL=https://hanwaydev.hanjinkal.com/ekp/service/openapi/

################## File Upload Section ##################
uploadDir=/data/gwstore/groupware/naonfiles/upload/
imageUploadDir=/data/gwstore/groupware/naonfiles/upload/
UPLOADBASE_DIR=/data/gwstore/groupware/naonfiles/upload/
ATTACH_DIR=/data/gwstore/groupware/naonfiles/upload/attach
BODY_DIR=/data/gwstore/groupware/naonfiles/upload/body
TMP_ATTACH_DIR=/data/gwstore/groupware/naonfiles/upload/tmp
fileboxUploadUseYn=N

################## File download seciton. ##################
charset=utf-8
uploadUrl=/upload
imageUploadUrl=/upload
UPLOADBASE_URL=/upload/
BODY_URL=/upload/body/
ATTACH_URL=/upload/attach/

################## Application Context Section ##################
context=/ekp
EKP_CONTEXT_PATH=/ekp
CONTEXT_NAME=ekp

################## Multi-lingual Section ##################
langSet=\uD55C\uAD6D\uC5B4$ko*English$en
defaultLang=ko
DEFAULT_LANG_KEY=ko
FORUM_NAME=ko#{\uCEE4\uBBA4\uB2C8\uD2F0}|en#{Community}|
LANGUAGE_SET=\uD55C\uAD6D\uC5B4$ko*English$en
DEFAULT_MULTILINGUAL_VALUE=nonamed
LOCALE_LANG=ko

################## Process Monitoring Section ##################
processLimitTime=1

################## Board Section ##################
fileSaveStorageYn=N

################## Editor Section ##################
editorType=namo
EDITOR_TYPE=namo
mobileEditorType=namo_mobile

################## Session Section ##################
fixedSessionYn=N
sessionTimeout=43200

################## Clustering Section ##################
gwSync=NOT
clusteredOthers=localhost

################## Login / Logout Section ##################
duplLoginYn=Y
loginType=3
loginIdTypeOfloginType2=1
loginHome=/hanjinkalMain/home/homGwMain
doLogoutPage=/main/home/homGwMain
otherHome=/view/home/other/homOtherMain
otherMoblHome=/moblkair/moapp/eapp/eapMain?menu=A6600
onlyLoginPageSslYn=N
loginRsaUseYn=Y
loginEnableTime=10
loginEnableUseYN=Y

################## Mail Server Section ##################
mailUseYn=N
mailDebugYn=false
mailLazySendYn=N
useJamesRmi=false
jamesRmiIp=127.0.0.1
jamesRmiPort=1099
useJamesApproval=false
USE_MAIL_PARSER_PROJECT_USE_YN=false
mailServer=127.0.0.1
smtpPort=25
smtpProtocol=smtp
imapPort=143
imapProtocol=imap
smtpMaxRecipientNum=100
mailTempDir=mailTempDir
SSLUseYn=false
MAIL_URL=https://hanwaydev.hanjinkal.com/ekp/scr/eml/emlMain
MAIL_POP3_URL=https://hanwaydev.hanjinkal.com/ekp/view/eml/emlPopMain
SMTP_TYPE=naon
MAIL_HOST=mail.
MAIL_DOMAIN=naonsoft.com
MAIL_PROTOCOL=https://
MAIL_INTERFACE=/interface/
PWD_HASH_AGLO_TYPE=NAON-SHA-256
HIERARCHICAL_MAPPING=true
MAIL_PROTOCOL_TIMEOUT=45

################## Search Server Section ##################
useSolrServer=false
emlSearchSolrUrl=https://127.0.0.1:8983/solr/mail/select
gwSearchSolrUrl=https://127.0.0.1:8983/solr

################## Wisenut Search Server Section ##################
gwWnUnifiedSearchUseYn=N
gwWnUnifiedSearchUrl=10.41.19.42
gwWnUnifiedSearchPort=7000
gwWnUnifiedSearchManagePort=7800
gwWnUnifiedSearchModules=gapp|N,app|Y,migapp|Y,bbs|N,mail|N,space|N,doc|N,not|N,smw|N,wor|N,org|N

################## Company Relation section ##################
REL_COMPANY_USE_YN=Y
USER_ID_CMP_DUPL=Y
APP_RELATION_YN=N

################## Mobile Push Section ##################
MOBILE_PUSH_USE_YN=N
MOBILE_DEVICE_CERT_USE_YN=N
mobilePushModule=FCM
mobilePushVer=702

################## Messenger Section ##################
messengerProtocol=N

################## TcpMessenger Section ##################
MESSENGER_SERVER_IP=127.0.0.1
MESSENGER_SERVER_PORT=14000
MESSENGER_SERVER_UNREAD_PORT=13998
MESSENGER_SERVER_NGW_PORT=13990

################## WebMessenger Section ##################
webMessengerUrl=https://msg.naonsoft.kr
webMessengerUploadUrl=https://msg.naonsoft.kr/webmsgr/api/cmm/file/fileDownload
webMessengerApiUrl=https://msg.naonsoft.kr/webmsgr/api
webMessengerUiUrl=https://msg.naonsoft.kr/webmsgr/ui

################## Portal Section ##################
DEFAULT_THEME_NAME=Navy


################## Mobile-APP Section ##################
MOBILE_MESSENGER_USE_YN=N
MOBILE_MESSENGER_FILE_TRANSFER_YN=N
MESSENGER_SERVER_TYPE=1
MOBILE_MESSENGER_IP_TYPE=IPV4
MESSENGER_SERVER_OS_BIT_TYPE=32
GROUPWARE_VERSION=7.0

################## Plugin Section ##################
SMS_USE_YN=N
FAX_USE_YN=N
DOC_BOX_PACKAGE=edms
SMS_TYPE=Daou
FAX_TYPE=Daou
FAX_SEND_FILE_PATH=
FAX_RECV_FILE_WEB_URL=

################## Groupware Logic Section ##################
IS_GROUPWARE_MAIN_USE=Y
PORTLET_GW_USE=Y
ATTEND_SYNC_YN=N
MAIL_USE_YN=N
UPLOAD_MODE=activex&flex
UPLOAD_SELECTED_TAB=activex
ORGANIZATION_MODE=real
TYPE_NAME=naongw
ENCRYPT_TYPE=naongw
RSS_AUTH_TYPE=naongw
NOTE_SEND_SERVER=N
SYSTEM_USER_ID=systemadmin
SERVER_TIMEZONE=9
BACKUP_QUOTA=2147483648

################## Google Data Sync Section ##################
CLIENT_ID_6=
CLIENT_SECRET_6=
GOOGLE_SYNC_BASE_TERM=12
GOOGLE_API_KEY=AIzaSyBNgDIMgGqA8lygm8T0wS6KHYN2C6WV4Zs
PARCEL_API_REGKEY=6d130455ee37e7a2d1308304274624

################## Socket io Server Section ##################
GROUPWARE_NOTICE_USE_YN=N
SOCKET_IO_SERVER_PORT=9090
SOCKET_IO_SERVER_SSL_YN=N
SOCKET_IO_SERVER_SSL_KEYSTORE=/opt/naon/app/apache2/conf/ssl/keystore.jks
SOCKET_IO_SERVER_SSL_KEYSTORE_PWD=@skdhsthvmxm!

################## Mobile-App Logo Section ##################
customizeResourceDir=/data/was/webapps/resources/custom/naon
customAppLogoUseYn=N

################## Exchange Server Section ##################
EXCHANGE_USE_YN=N
EXCHANGE_MAX_CONNECTION_POOL=1024
EXCHANGE_URI=https://ex.naonsoft.kr/ews/Exchange.asmx
EXCHANGE_VERSION=2016

################## Approval Section ##################
APP_SYS=E
APPROVAL_CNT=eapp
APP_INTRLCK_CIPHER=S
APP_GROUP_MANAGE_USE_YN=N

################## G-Approval Section ##################
APP_HWP_SERVER_IP=127.0.0.1
APP_HWP_SERVER_PORT=9090
RELAY_HOME=/opt/naon/gw/relay
SEND_ORG_CODE=B000000
SEND_ID=B000000
APP_INNER_RELAY_YN=N
GAP_HWP_TYPE=A
WEB_HWP_SERVER=https://127.0.0.1/webhwpctrl
WEB_HWP_PAGE_URL=/service/app/gapp/document/hwpctrlmain

################## Form-Builder Section ##################
frmMacroVer=7.x
useLinkApi=Y
defaultGappFormDir=/data/was/jboss/app/ekp/jsp/biz/common/hwpcontrol/naongw_xml

server_environment=DEVELOPMENT
################## Debugging Section #######################
#printOutErrorMessageYn=Y

################## Survey Section ##################
SURVEY_EXAM_USE_YN=Y

################## Smartwork Section #####################
SPREAD_SHEET_USE_YN=Y
spreadJSVer=13.1.1
GOOGLE_MAP_USE_YN=Y

################## Javscript Section #####################
jsVerStaicUseYn=N

################## image_convert Section ##################
IMAGE_CONVERT_USE_YN=Y
IMAGE_CONVERT_SERVER=https://ihanwaydev.hanjinkal.com
IMAGE_CONVERT_PRODUCT=

PDF_CONVERT_SAVE_URL=http://127.0.0.1:8888
#################### Post Portlet Section ###################
postRetentionPeriod=30

################### ORG Sync Section #########################
ORG_DATA_SYNC_YN=Y
ORG_UPDATE_SYNC_USE_YN=N
ORG_UPDATE_SYNC_DATE_TERM=1
GSUITE_ORG_SYNC_YN=N
SSO_ORG_SYNC_YN=N

################### AppStore Section #########################
APPSTORE_MNG_USE_YN=N
APPSTORE_FORGERY_CHK_USE_YN=N

################### jwt Section #########################
jwtKey=Z8YDECgq/jJPN/5egtJ1tckKUiefF7tM8NnzHmFOOpk=

################### HR_API_URL #########################
HR_API_URL=https://hrapplyformdev.koreanair.com
#HR_API_PRD_URL=https://hrapplyform.koreanair.com

################## Google gsuite Section ##################
HIST_APPROVAL_USER_ID=dev_hghanwaymail@hanjinkal.com
GSUITE_ADMIN_USER_ID=approvaladmin@hanjinkal.com
GSUITE_DOMAIN=hanjinkal.com
#GSUITE_MAIL_DOMAIN_REPLACE=
GSUITE_SERVICE_ACCOUNT_EMAIL=hanwaydev-svc-account@hanwaydev-hanjinkal.iam.gserviceaccount.com
GSUITE_SERVICE_ACCOUNT_KEY_FILE_PATH=file:/data/was/jboss/app/saml

GOOGLE_MY_APPROVAL_FOLDER_NAME=ApprovalDev
GOOGLE_APP_INTRCK_EXECUTOR_CNT=10

################## Google Email Account Section (hist1 ~ hist2) ##################
GSUITE_APPROVAL_USER_ID=hghanwaymail
GSUITE_APPROVAL_USER_ID_COUNT=9
GSUITE_APPROVAL_USER_ID_COUNT_DEFAULT_DIGIT=2
GSUITE_APPROVAL_USER_ID_ALIAS_NAME=Hanway \uC54C\uB9BC
GSUITE_MAIL_LIMIT_USE_YN=N

##################  Google SSO Configuration ##################
saml.useYn=Y
saml.idp.metadata-trust=false
saml.idp.metadata-require-signature=false
saml.idp.metadata-url=/saml/dev/GoogleIDPMetadata.xml
saml.idp.name=google
saml.sp.use-entity=true
saml.sp.entityBaseUrl=https://hanwaydev.hanjinkal.com/ekp
saml.sp.mobileEntityBaseUrl=https://mhanwaydev.hanjinkal.com/ekp
saml.sp.entity-id=hghanwaydev
saml.sp.mobile-entity-id=hgmhanwaydev

saml.sp.login-url=/hanjinkalMain/home/homGwMain
saml.sp.logout-url=https://accounts.google.com/logout
saml.sp.error-url=/view/login/noAuth
saml.sp.maxAuthenticationAge=31536000
saml.sp.forceAuthn=false
saml.sp.responseSkew=120
saml.sp.key-store.file=file:/data/was/jboss/app/ssl/tomcat.keystore
saml.sp.key-store.alias=tomcat
saml.sp.logout-click-url=https://accounts.google.com/logout
saml.sp.signing-algorithm=http://www.w3.org/2000/09/xmldsig#rsa-sha1

##################  Google SSO Configuration ##################
redis.host=hgdev-redis.5jeeot.0001.apn2.cache.amazonaws.com
redis.port=6980
redis.jedis.maxTotal=100
redis.jedis.maxIdle=100
redis.jedis.minIdle=30

################## \uBAA8\uBC14\uC77C URL ##################
MOBILE_URL=https://mhanwaydev.hanjinkal.com/ekp/moblview/mologin/userLogin
MOBILE_MAIN_URL=https://mhanwaydev.hanjinkal.com/ekp/moblpotal/mohome/moblHomGwMain
MOBILE_TYPE=iphone,ipod,android,blackberry,windows ce,nokia,webos,opera mini,sonyericsson,opera mobi,iemobile,ipad
TABLET_TYPE=
PC_DEVICE=win16|win32|win64|mac|macintel
MOBILE_MAIN_PAGE=/moblpotal/mohome/moblHomGwMain
MOBILE_LOGIN_PAGE=/moblview/mologin/userLogin

################## WEB URL ##################
WEB_MAIN_URL=https://hanwaydev.hanjinkal.com/ekp/hanjinkalMain/home/homGwMain

SYSLOGIN_TRANSFER_USE_YN=Y

AWS_SECRET_MANAGER_NAME=hg_dev_secm_app

#\uC774\uAD00 \uAD00\uB828 BOXID
MIGRATION_BOX=AB1879925660207786205,AB1893035416963659575,AB18938543606098552,AB1894448022743927442,AB1895738830634144682
SHARE_BOX=AB1869633382946507800

################## \uAE30\uC548 PROCESSID ##################
CONSULTATION_PROCESS_ID=AP2347938821088784422

################## \uC775\uC6D4\uD734\uAC00\uC2E0\uCCAD\uC11C WORK_ID ##################
NEXT_MONTH_VAC_WORK_ID=AW483283793558228963

################## \uC2DC\uC2A4\uD15C\uBCF4\uC644\uC758\uB8B0\uC11C WORK_ID ##################
SYSTEM_SUPPLEMENT_REQUEST_WORK_ID=AW27879899746910223219

################## \uD310\uB9E4\uAC00\uC2B9\uC778 \uC778\uD130\uD398\uC774\uC2A4ID ##################
PRICE_FORM_INSERT_INFO_IF_ID=228523560413005004

################## \uD734\uC9C1, \uC0AC\uC9C1 \uC2E0\uCCAD\uC11C(\uC77C\uBC18) FORM_ID ##################
LEVWORK_FORM_ID=30403589405762871582

RESIGN_FORM_ID=30497756737982216470

### \uBC95\uC778\uC778\uAC10 \uBC0F \uBC95\uC778\uC99D\uBA85\uC11C \uC2E0\uCCAD & \uC0AC\uC6A9\uC778\uAC10 \uBC0F \uC9C1\uC778 \uC2E0\uCCAD(\uD1B5\uD569)
SEAL_CERTIFICATE_FROM_ID=21002805462194023803
### \uC0AC\uAC01\uC9C1\uC778|\uBC95\uC778\uC778\uAC10 \uC740 \uBB38\uC11C \uBCC0\uACBD \uC2DC \uBCC0\uACBD \uC0AC\uC720 \uC785\uB835 \uD31D\uC5C5 \uC548\uB738
DOC_CHANGE_NO_POPUP_FORM_IDS=30473796906237148|69789048945653702

# \uC778\uAC10 \uBC0F \uBC95\uC778\uC99D\uBA85\uC11C \uC591\uC2DD formid
DOC_SEAL_CORP_FORM_IDS=|48800996458685481510|44550958525071237092|48801057798929503075|48801027514396168325|14175255037735538334|48800727086978445584|48800815932012598148|48800905719922494508|48800756367129157523|36719885720584814122|48800846488050366811|48801087995864924682|48800875952751648233|48800966039651238093|48800935934701559392|36719852573290055759|48800693251448686432|18870779209598373711|38645459707796898021|39341512586146669121|48800786363720793424|14537863852984694253|1808704587729074292|
DOC_SEAL_CORP_FORM_ID_LJ=1808704587729074292

#\uC774\uAD00 \uAD00\uB828 hanway location
HANWAYFILE=/was/hanwayfile

############## AWS COGNITO ################
ROLE_ARN=arn:aws:iam::129549734827:role/DEV-APRV
ROLE_NAME=DEV-APRV
PORTAL_AWS_TOKEN_URL=https://auth-dev-hwy.koreanair.com/oauth2/token
PORTAL_SECRET_MANAGE_ARN=arn:aws:secretsmanager:ap-northeast-2:993398491107:secret:cognito/dev/hwy/approval-nqGbwL
PORTAL_SECRET_MANAGE_REGION=ap-northeast-2
PORTAL_LANG_API_URL=https://vpce-02222b27b5af2d20b-j3q7auih.execute-api.ap-northeast-2.vpce.amazonaws.com/dev/userlang?employeeNumber=

################## METADATA DOCURL ##################
DOC_URL_COL_ID=16173486719163349

################## \uAC1D\uC2E4\uC5F0\uCC28 FORM_ID ##################
ANNUAL_LEAV_FORM_ID=590970028560782252

################## SKD SWAP FORM_ID ##################
SKD_SWAP_FORM_ID=1007030129627002156

############## AWS S3 ################
S3_ROLE_YN=Y

################## OPENAPI Section ##################
ORG_DATA_SYNC_CRYPT_KRY=C300210723/openapi/hanjin_crypt_key.txt

################## \uC804\uC790\uACC4\uC57D ##################
NEW_CONTRACT_FORM_ID=69037119799217512351
RESIGN_CONTRACT_FORM_ID=69091648747235193175

################## \uACC4\uC57D\uC11C \uAC80\uD1A0 \uACB0\uACFC/\uBC95\uB960 \uC790\uBB38 \uD68C\uC2E0 \uC591\uC2DD FORM_ID ##################
CONTRACT_REVIEW_FORM_ID=36289576199559231
CONTRACT_REVIEW_WORK_ID=AW3405806355634452
CONTRACT_REVIEW_COL_ID=16732228211964154

################## \uACC4\uC57D\uC11C \uAC80\uD1A0 \uACB0\uACFC/\uBC95\uB960 \uC790\uBB38 \uD68C\uC2E0 \uAC80\uC99D \uD544\uC218 \uD68C\uC0AC \uBC0F \uBD80\uC11C ##################
CONTRACT_REVIEW_VERIFY_REQURIED=C171084155