#--------------------------------------------------------------------------------------------------
#
#                                 Groupware Global Properties
#
#
#--------------------------------------------------------------------------------------------------

################## Groupware Section ##################
gwVer=
CMP_ID=

################## Database Section ##################
# oracle / mysql / mssql
dbtypeLowerCase=mysql
jndiName=java:comp/env/jdbc/NaonekpDS

################## JUNIT TEST Section ##################
jdbc.driverClassName=
jdbc.url=
jdbc.username=
jdbc.password=

################## Protocol section ##################
ngwProtocol=https://
EKP_PROTOCOL=https://

################## URL section ##################
ngwProtocolUrl=
imageServer=
mobileImageServer=
mobilePrefix=m
MOBILE_HOST=m
MOBILE_MAIL_HOST=m
SKIN_URL=
SKIN_ROOT=/style
EKP_URL=/ekp
LOGIN_URL=/ekp/view/login/userLogin
WEB_SERVER=
IMAGE_URL=/ekp
DAV_OPENAPI_URL=/ekp/service/openapi/

################## File Upload Section ##################
uploadDir=/data/gwstore/groupware/naonfiles/upload/
imageUploadDir=/data/gwstore/groupware/naonfiles/upload/
UPLOADBASE_DIR=/data/gwstore/groupware/naonfiles/upload/
ATTACH_DIR=/data/gwstore/groupware/naonfiles/upload/attach
BODY_DIR=/data/gwstore/groupware/naonfiles/upload/body
TMP_ATTACH_DIR=/data/gwstore/groupware/naonfiles/upload/tmp
fileboxUploadUseYn=N

################## File download seciton. ##################
charset=utf-8
uploadUrl=/upload
imageUploadUrl=/upload
UPLOADBASE_URL=/upload/
BODY_URL=/upload/body/
ATTACH_URL=/upload/attach/

################## Application Context Section ##################
context=/ekp
EKP_CONTEXT_PATH=/ekp
CONTEXT_NAME=ekp

################## Multi-lingual Section ##################
langSet=\uD55C\uAD6D\uC5B4$ko*English$en
defaultLang=ko
DEFAULT_LANG_KEY=ko
FORUM_NAME=ko#{\uCEE4\uBBA4\uB2C8\uD2F0}|en#{Community}|
LANGUAGE_SET=\uD55C\uAD6D\uC5B4$ko*English$en
DEFAULT_MULTILINGUAL_VALUE=nonamed
LOCALE_LANG=ko

################## Process Monitoring Section ##################
processLimitTime=1

################## Board Section ##################
fileSaveStorageYn=N

################## Editor Section ##################
editorType=namo
EDITOR_TYPE=namo
mobileEditorType=namo_mobile

################## Session Section ##################
fixedSessionYn=N
sessionTimeout=43200

################## Clustering Section ##################
gwSync=NOT
clusteredOthers=localhost

################## Login / Logout Section ##################
duplLoginYn=Y
loginType=3
loginIdTypeOfloginType2=1
loginHome=/hanjinkalMain/home/homGwMain
doLogoutPage=/main/home/homGwMain
otherHome=/view/home/other/homOtherMain
otherMoblHome=/moblkair/moapp/eapp/eapMain?menu=A6600
onlyLoginPageSslYn=N
loginRsaUseYn=Y
loginEnableTime=10
loginEnableUseYN=Y

################## Mail Server Section ##################
mailUseYn=N
mailDebugYn=false
mailLazySendYn=N
useJamesRmi=false
jamesRmiIp=127.0.0.1
jamesRmiPort=1099
useJamesApproval=false
USE_MAIL_PARSER_PROJECT_USE_YN=false
mailServer=127.0.0.1
smtpPort=25
smtpProtocol=smtp
imapPort=143
imapProtocol=imap
smtpMaxRecipientNum=100
mailTempDir=mailTempDir
SSLUseYn=false
MAIL_URL=/ekp/scr/eml/emlMain
MAIL_POP3_URL=/ekp/view/eml/emlPopMain
SMTP_TYPE=naon
MAIL_HOST=mail.
MAIL_DOMAIN=naonsoft.com
MAIL_PROTOCOL=https://
MAIL_INTERFACE=/interface/
PWD_HASH_AGLO_TYPE=NAON-SHA-256
HIERARCHICAL_MAPPING=true
MAIL_PROTOCOL_TIMEOUT=45

################## Search Server Section ##################
useSolrServer=false
emlSearchSolrUrl=
gwSearchSolrUrl=

################## Wisenut Search Server Section ##################
gwWnUnifiedSearchUseYn=N
gwWnUnifiedSearchUrl=
gwWnUnifiedSearchPort=7000
gwWnUnifiedSearchManagePort=7800
gwWnUnifiedSearchModules=gapp|N,app|Y,migapp|Y,bbs|N,mail|N,space|N,doc|N,not|N,smw|N,wor|N,org|N

################## Company Relation section ##################
REL_COMPANY_USE_YN=Y
USER_ID_CMP_DUPL=Y
APP_RELATION_YN=N

################## Mobile Push Section ##################
MOBILE_PUSH_USE_YN=N
MOBILE_DEVICE_CERT_USE_YN=N
mobilePushModule=FCM
mobilePushVer=702

################## Messenger Section ##################
messengerProtocol=N

################## TcpMessenger Section ##################
MESSENGER_SERVER_IP=
MESSENGER_SERVER_PORT=14000
MESSENGER_SERVER_UNREAD_PORT=13998
MESSENGER_SERVER_NGW_PORT=13990

################## WebMessenger Section ##################
webMessengerUrl=https://msg.naonsoft.kr
webMessengerUploadUrl=https://msg.naonsoft.kr/webmsgr/api/cmm/file/fileDownload
webMessengerApiUrl=https://msg.naonsoft.kr/webmsgr/api
webMessengerUiUrl=https://msg.naonsoft.kr/webmsgr/ui

################## Portal Section ##################
DEFAULT_THEME_NAME=Navy


################## Mobile-APP Section ##################
MOBILE_MESSENGER_USE_YN=N
MOBILE_MESSENGER_FILE_TRANSFER_YN=N
MESSENGER_SERVER_TYPE=1
MOBILE_MESSENGER_IP_TYPE=IPV4
MESSENGER_SERVER_OS_BIT_TYPE=32
GROUPWARE_VERSION=7.0

################## Plugin Section ##################
SMS_USE_YN=N
FAX_USE_YN=N
DOC_BOX_PACKAGE=edms
SMS_TYPE=Daou
FAX_TYPE=Daou
FAX_SEND_FILE_PATH=
FAX_RECV_FILE_WEB_URL=

################## Groupware Logic Section ##################
IS_GROUPWARE_MAIN_USE=Y
PORTLET_GW_USE=Y
ATTEND_SYNC_YN=N
MAIL_USE_YN=N
UPLOAD_MODE=activex&flex
UPLOAD_SELECTED_TAB=activex
ORGANIZATION_MODE=real
TYPE_NAME=naongw
ENCRYPT_TYPE=naongw
RSS_AUTH_TYPE=naongw
NOTE_SEND_SERVER=N
SYSTEM_USER_ID=systemadmin
SERVER_TIMEZONE=9
BACKUP_QUOTA=2147483648

################## Google Data Sync Section ##################
CLIENT_ID_6=
CLIENT_SECRET_6=
GOOGLE_SYNC_BASE_TERM=12
GOOGLE_API_KEY=AIzaSyBNgDIMgGqA8lygm8T0wS6KHYN2C6WV4Zs
PARCEL_API_REGKEY=6d130455ee37e7a2d1308304274624

################## Socket io Server Section ##################
GROUPWARE_NOTICE_USE_YN=N
SOCKET_IO_SERVER_PORT=9090
SOCKET_IO_SERVER_SSL_YN=N
SOCKET_IO_SERVER_SSL_KEYSTORE=/opt/naon/app/apache2/conf/ssl/keystore.jks
SOCKET_IO_SERVER_SSL_KEYSTORE_PWD=@skdhsthvmxm!

################## Mobile-App Logo Section ##################
customizeResourceDir=/data/was/webapps/resources/custom/naon
customAppLogoUseYn=N

################## Exchange Server Section ##################
EXCHANGE_USE_YN=N
EXCHANGE_MAX_CONNECTION_POOL=1024
EXCHANGE_URI=https://ex.naonsoft.kr/ews/Exchange.asmx
EXCHANGE_VERSION=2016

################## Approval Section ##################
APP_SYS=E
APPROVAL_CNT=eapp
APP_INTRLCK_CIPHER=S
APP_GROUP_MANAGE_USE_YN=N

################## G-Approval Section ##################
APP_HWP_SERVER_IP=127.0.0.1
APP_HWP_SERVER_PORT=9090
RELAY_HOME=/opt/naon/gw/relay
SEND_ORG_CODE=B000000
SEND_ID=B000000
APP_INNER_RELAY_YN=N
GAP_HWP_TYPE=A
WEB_HWP_SERVER=https://127.0.0.1/webhwpctrl
WEB_HWP_PAGE_URL=/service/app/gapp/document/hwpctrlmain

################## Form-Builder Section ##################
frmMacroVer=7.x
useLinkApi=Y
defaultGappFormDir=/data/was/jboss/app/ekp/jsp/biz/common/hwpcontrol/naongw_xml

server_environment=DEVELOPMENT
################## Debugging Section #######################
#printOutErrorMessageYn=Y

################## Survey Section ##################
SURVEY_EXAM_USE_YN=Y

################## Smartwork Section #####################
SPREAD_SHEET_USE_YN=Y
spreadJSVer=13.1.1
GOOGLE_MAP_USE_YN=Y

################## Javscript Section #####################
jsVerStaicUseYn=N

################## image_convert Section ##################
IMAGE_CONVERT_USE_YN=Y
IMAGE_CONVERT_SERVER=https://ihanwaydev.hanjinkal.com
IMAGE_CONVERT_PRODUCT=

PDF_CONVERT_SAVE_URL=http://127.0.0.1:8888
#################### Post Portlet Section ###################
postRetentionPeriod=30

################### ORG Sync Section #########################
ORG_DATA_SYNC_YN=Y
ORG_UPDATE_SYNC_USE_YN=N
ORG_UPDATE_SYNC_DATE_TERM=1
GSUITE_ORG_SYNC_YN=N
SSO_ORG_SYNC_YN=N

################### AppStore Section #########################
APPSTORE_MNG_USE_YN=N
APPSTORE_FORGERY_CHK_USE_YN=N

################### jwt Section #########################
jwtKey=Z8YDECgq/jJPN/5egtJ1tckKUiefF7tM8NnzHmFOOpk=

################### HR_API_URL #########################
HR_API_URL=


################## WEB URL ##################
WEB_MAIN_URL=

SYSLOGIN_TRANSFER_USE_YN=Y

AWS_SECRET_MANAGER_NAME=
